name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - scipy=1.13.1
  - xarray=2024.06.0
  - matplotlib=3.8.4
  - pyproj=3.6.1
  - netcdf4=1.7.1
  - ipython=8.24.0
  - fortran-compiler
  - make
  - pkg-config
  - netcdf-fortran
  - eccodes=2.35.0
